name: Share between steps
on: [workflow_dispatch]
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - id: source
        run: echo "result=Hello from github_output" >> "${GITHUB_OUTPUT}"
      - env:
         RESULT: ${{ steps.source.outputs.result }}
        run: echo "${RESULT}"
      - run: echo "RESULT2=Hello from github_env" >> "${GITHUB_ENV}"
      - run: echo "${RESULT2}"
